---
    - include_vars: secrets.yml
      no_log: true
    
    - name: Install MySQL database
      apt: name={{ item }} state=latest force=yes
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes
        
    - name: Make sure pymysql is present
      become: true # needed if the other tasks are not played as root
      pip:
        name: pymysql
        state: present
        
    - name: Create Application Database
      mysql_db: name={{ db_name }} state=present

    - name: Cretae Database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'
