---
    - include_vars: secrets.yml
      no_log: true
    
    - name: Install MySQL database
      apt: name={{ item }} state=latest force=yes
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes
        
    - name: Make sure pymysql is present
      become: true # needed if the other tasks are not played as root
      pip:
        name: pymysql
        state: present
  
    - name: update mysql root password for all root accounts  
      mysql_user:  
        name: root  
        host: "{{ item }}"  
        password: "{{ mysql_root_password }}"  
        login_user: root  
        login_password: "{{ mysql_root_password }}"  
        check_implicit_admin: yes  
        priv: "*.*:ALL,GRANT"  
      with_items:  
      - "{{ ansible_hostname }}"  
      - 127.0.0.1  
      - ::1  
      - localhost

    - name: create a new database  
      mysql_db: 
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
   
    - name: Create Database user      
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'
